[workspace]
members = ["middleware-wasm", "cli", "forward-proxy"]
resolver = "2"

[profile.release.middleware-wasm]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
strip = "debuginfo"
targets = ["wasm32-unknown-unknown"]
