[package]
name = "layer8-middleware-rs"
version = "0.1.4"
edition = "2021"
authors = ["Osoro Bironga <fanosoro@gmail.com>"]
repository = "github.com/muse254/layer8-middleware-rs"
license = "GNU GPLv2"
readme = "README.md"
categories = ["wasm"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"

[lib]
crate-type = ["cdylib"]

[dependencies]
web-sys = { version = "0.3.70" }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
lazy_static = "1.5.0"
layer8-interceptor-rs = { git = "https://github.com/muse254/layer8-interceptor-rs", features = [
    "no-js",
], branch = "main" }
serde = "1.0.210"
serde_json = "1.0.128"
base64 = { version = "0.22" }
js-sys = "0.3"
serde-wasm-bindgen = "0.6.5"
url = "2.5.2"
mime-sniffer = "0.1.2"
rand = { version = "0.8.5", features = ["small_rng"] }
form_urlencoded = "1.2.1"

[dev-dependencies]
uuid = "1.10.0"
wasm-bindgen-test = "0.3"
jsonwebtoken = "9"
