name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.81.0  # Related: <https://github.com/cloudflare/workers-rs/issues/668>, <https://github.com/cloudflare/workers-sdk/issues/7208>
          override: true
          override-file: Cargo.toml
          target: wasm32-unknown-unknown

      - name: Build
        run: |
          # If macOs install llvm with brew
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install llvm
            export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
            export CC=/opt/homebrew/opt/llvm/bin/clang
            export AR=/opt/homebrew/opt/llvm/bin/llvm-ar
          fi
          cargo install wasm-pack
          wasm-pack build --target nodejs 
          sudo apt-get -y update && sudo apt-get -y install gawk
          gawk '{ if (NR == 14) { print $0 "\"./snippets/*\", "; } else { print $0; } }' ./pkg/package.json > temp.json && mv temp.json ./pkg/package.json 
         
      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Publish to NPM 
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          registry: https://registry.npmjs.org
          access: public
          package: ./pkg
