name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-file: Cargo.toml
          target: wasm32-unknown-unknown

      - name: Build
        run: |
          cargo install wasm-pack
          wasm-pack build --target nodejs
          mkdir pkg/src
          cp src/js_utility_functions.js pkg
          sudo apt-get -y update && sudo apt-get -y install gawk
          gawk '{ if (NR == 13) { print $0 " \"js_utility_functions.js\", "; } else { print $0; } }' ./pkg/package.json > temp.json && mv temp.json ./pkg/package.json 
          gawk -i inplace 'NR==5 { $0 = "const { single_fn, array_fn,  as_json_string, request_set_header, request_set_body, request_set_url, request_get_url, request_headers, request_callbacks, request_get_body_string, response_add_header, response_set_status, response_set_status_text, response_set_body, response_get_headers, response_get_status, response_get_status_text } = require(`./js_utility_functions.js`);" } { print }' ./pkg/layer8_middleware_rs.js  
    
      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Publish to NPM 
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          registry: https://registry.npmjs.org
          access: public
          package: ./pkg
